### ISSUE TITLE
Get graphics basics set up

### ISSUE THREAD

**Issue by agnacore** [agnacore/Spaceship#3]
Basically the frame, stage, that stuff

**Comment by agnacore** [comment]
the connection to logic needs to be done *somewhere*, ideally the logic controls the graphics

**Comment by c-m-green** [comment]
So what I'm thinking is we have the model class (Player, Enemy, etc.) [have a](https://stackoverflow.com/questions/36162714/what-is-the-difference-between-is-a-relationship-and-has-a-relationship-in) sprite or kind of image object. The controller class would then be in charge of updating the ship's position.

We could create or get images to use for each ship type. For now, I gave them JavaFX rectangles. (See the associated PR.)

Ultimately, we may want to look into JavaFX animations, which I know nothing about at the moment.

**Comment by c-m-green** [comment]
@agnacore I think what I'll actually do is keep my assignment here and assign you to the pull request instead.
